version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
  test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      # special step to restore the dependency cache
      - restore_cache:
          key: v2-{{ checksum "package.json" }}
      # special step to save the dependency cache
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Tests and Run Code Coverage with NYC
          command: |
            echo "Generate Code Coverage"
            npm test
            echo "Show the coverage"
            npm run coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master Branch to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
        